repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the sorting with isort.
      - id: ruff
        name: ruff-isort
        args: ["--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
    